{% set name = "in_place" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 503048e91e0736cb092787c8017dce1328a62421f8fb81c29d25854c355af5ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - in_place

about:
  home: https://github.com/jwodder/inplace
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: In-place file processing in Python
  description: |
    The in_place module provides an InPlace class for reading & 
    writing a file "in-place": data that you write ends up at the 
    same filepath that you read from, and in_place takes care of 
    all the necessary mucking about with temporary files for you.

extra:
  recipe-maintainers:
    - jwodder
    - druvus
