{% set name = "in_place" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b0b2b9073c3e7a116f819f7f51711b56216b24b67be57cfcdfe717400bc8743

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - pytest
    - pytest-cov
    - python {{ python_min }}
  source_files:
    - test
    - tox.ini
  imports:
    - in_place
  commands:
    - python -m pytest -vv test

about:
  home: https://github.com/jwodder/inplace
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: In-place file processing in Python
  description: |
    The in_place module provides an InPlace class for reading &
    writing a file "in-place": data that you write ends up at the
    same filepath that you read from, and in_place takes care of
    all the necessary mucking about with temporary files for you.
  dev_url: https://github.com/jwodder/inplace

extra:
  recipe-maintainers:
    - jwodder
    - druvus
